#!/usr/bin/env bash
# Connect the SSF Guide app to an existing Traefik reverse proxy (e.g. the
# one shipped with n8n) so the domain gets routed + HTTPS automatically.
#
# Safe by design: only ADDS labels/network to the ssf-guide app container.
# Never modifies the Traefik container or any other site.
#
# Run from anywhere:  bash /opt/ssf-guide/deploy/connect-traefik.sh
set -euo pipefail
cd "$(dirname "$0")/.."

DOMAIN="${SITE_DOMAIN:-$(grep -oP '^SITE_DOMAIN=\K.*' .env 2>/dev/null || echo ssf.digitalsolutionnepal.com)}"

TRAEFIK=$(docker ps --format '{{.Names}}' | grep -i traefik | head -1)
if [ -z "$TRAEFIK" ]; then
  echo "❌ No running Traefik container found."; exit 1
fi

NET=$(docker inspect "$TRAEFIK" --format '{{range $k,$v := .NetworkSettings.Networks}}{{$k}} {{end}}' | awk '{print $1}')
CMD=$(docker inspect "$TRAEFIK" --format '{{json .Config.Cmd}}{{json .Config.Entrypoint}}' 2>/dev/null || true)

RESOLVER=$(echo "$CMD" | grep -oE 'certificatesresolvers\.[a-zA-Z0-9_-]+' | head -1 | cut -d. -f2 || true)
EP_WEB=$(echo "$CMD" | grep -oE 'entry[Pp]oints\.[a-zA-Z0-9_-]+\.address=:80' | head -1 | cut -d. -f2 || true)
EP_SECURE=$(echo "$CMD" | grep -oE 'entry[Pp]oints\.[a-zA-Z0-9_-]+\.address=:443' | head -1 | cut -d. -f2 || true)
RESOLVER=${RESOLVER:-mytlschallenge}
EP_WEB=${EP_WEB:-web}
EP_SECURE=${EP_SECURE:-websecure}

echo "==> Traefik container: $TRAEFIK"
echo "==> Docker network:    $NET"
echo "==> Entrypoints:       $EP_WEB (80), $EP_SECURE (443)"
echo "==> Cert resolver:     $RESOLVER"
echo "==> Domain:            $DOMAIN"

# migrate away from the old custom-named file if present
rm -f docker-compose.traefik.yml

cat > docker-compose.override.yml <<EOF
# Generated by deploy/connect-traefik.sh — attaches the app to the existing
# Traefik proxy. Regenerate by re-running the script.
services:
  app:
    networks:
      - default
      - traefik_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=${NET}
      - traefik.http.routers.ssfguide.rule=Host(\`${DOMAIN}\`)
      - traefik.http.routers.ssfguide.entrypoints=${EP_SECURE}
      - traefik.http.routers.ssfguide.tls=true
      - traefik.http.routers.ssfguide.tls.certresolver=${RESOLVER}
      - traefik.http.routers.ssfguide-http.rule=Host(\`${DOMAIN}\`)
      - traefik.http.routers.ssfguide-http.entrypoints=${EP_WEB}
      - traefik.http.services.ssfguide.loadbalancer.server.port=3000

networks:
  traefik_net:
    external: true
    name: ${NET}
EOF

docker compose up -d db app

echo ""
echo "✅ Connected. Once the DNS A record for ${DOMAIN} points at this VPS,"
echo "   Traefik will fetch the HTTPS certificate automatically."
echo "   Test:  curl -I https://${DOMAIN}"
