import type { FaqItem } from "./types";

const LAST_VERIFIED = "2026-07-11";

export const faqs: FaqItem[] = [
  {
    slug: "31-percent-kaha-jancha",
    question: "SSF मा जम्मा हुने ३१% रकम कहाँ जान्छ?",
    answerBlocks: [
      {
        type: "p",
        text: "चार योजनामा बाँडिन्छ (५औँ संशोधन): औषधि उपचार/मातृत्व १.२०%, दुर्घटना/अशक्तता ०.८०%, आश्रित परिवार ०.६७%, वृद्ध अवस्था २८.३३% (निवृत्तभरण २०% + अवकाश सुविधा ८.३३%)। सबैभन्दा ठूलो भाग तपाईंकै वृद्धावस्था बचतमा जान्छ।",
      },
    ],
    categorySlug: "yogdan-ra-badfad",
    userCategories: ["employee", "contributor"],
    popular: true,
    relatedArticleSlug: "31-pratishat-kaha-jancha",
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "jagir-chadepachi-paisa",
    question: "जागिर छाडेपछि SSF को पैसा के हुन्छ?",
    answerBlocks: [
      {
        type: "p",
        text: "अवकाश सुविधा योजनाको रकम (८.३३% + स्वेच्छिक थप + हस्तान्तरित) रोजगारी अन्त्यमा एकमुष्ट पाइन्छ। निवृत्तभरण योजनाको रकम (२०%) ६० वर्षपछि मासिक पेन्सनका रूपमा आउँछ — १८० महिना नपुगेकाले ६० वर्षमा एकमुष्ट वा पेन्सन रोज्न पाउँछन्। नयाँ SSF-सूचीकृत जागिरमा गए उही SSN मा योगदान निरन्तर चल्छ।",
      },
    ],
    categorySlug: "pension-ra-retirement",
    userCategories: ["employee", "contributor"],
    popular: true,
    relatedArticleSlug: "jagir-chadepachi-ke-huncha",
    videoIds: ["Q4SrXAtj074"],
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "pension-kahile-paincha",
    question: "SSF बाट Pension कहिले पाइन्छ?",
    answerBlocks: [
      {
        type: "p",
        text: "६० वर्ष उमेर पूरा भएपछि, कम्तीमा १८० महिना (१५ वर्ष) योगदान गरेको भए। रकम: (निवृत्तभरण खातामा जम्मा + लगानी प्रतिफल) ÷ १६० = आजीवन मासिक पेन्सन, मुद्रास्फीति समायोजनसहित।",
      },
    ],
    categorySlug: "pension-ra-retirement",
    userCategories: ["employee", "contributor"],
    popular: true,
    relatedArticleSlug: "pension-ra-retirement-guide",
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "bidesh-bata-yogdan",
    question: "विदेशमा हुनेले SSF मा कसरी योगदान गर्ने?",
    answerBlocks: [
      {
        type: "p",
        text: "श्रम स्वीकृति लिँदा नै सूचीकरण हुन्छ; विदेशमा भइसकेकाले SOSYS/mobile app बाट online निवेदन दिन सक्छन्। योगदान औद्योगिक न्यूनतम पारिश्रमिकको कम्तीमा २१.३३% (३ गुणासम्म रोज्न मिल्ने) — बैंक वा डिजिटल माध्यमबाट जम्मा गर्न सकिन्छ।",
      },
    ],
    categorySlug: "baideshik-rojgari",
    userCategories: ["foreign"],
    popular: true,
    relatedArticleSlug: "foreign-employment-guide",
    videoIds: ["uEKO8zmFEHg"],
    sourceKeys: ["foreign-procedure-2079"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "kyc-kina-avashyak",
    question: "KYC Verification किन आवश्यक हुन्छ?",
    answerBlocks: [
      {
        type: "p",
        text: "सम्पत्ति शुद्धीकरण निवारण कानुन र SSF को AML/CFT नीति, २०८२ बमोजिम पहिचान प्रमाणित नगरी सुविधा भुक्तानी हुँदैन — वास्तविक पहिचान नभएसम्म सुविधा निलम्बनसमेत हुन सक्छ (नियमावली २०७५, नियम १०)। KYC पूरा गरे मात्र दाबी र भुक्तानी सहज हुन्छ।",
      },
    ],
    categorySlug: "kyc-profile-nominee",
    userCategories: ["contributor", "foreign"],
    popular: true,
    relatedArticleSlug: "kyc-profile-claim-guide",
    videoIds: ["EZS--UrRV04"],
    sourceKeys: ["aml-policy-2082"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "contribution-nadekhiema",
    question: "Contribution नदेखिएमा के गर्ने?",
    answerBlocks: [
      {
        type: "steps",
        items: [
          "SOSYS मा login गरी योगदान विवरण (contribution history) जाँच्नुहोस्",
          "रोजगारदातालाई payroll विवरण र भौचर देखाउन भन्नुहोस्",
          "रोजगारदाताले जम्मा नगरेको देखिए SSF मा उजुरी/निवेदन दिनुहोस् — कोषले १०% ब्याजसहित असुल गर्छ",
          "योगदान नबुझाएको अवधिमा दुर्घटना/मृत्यु भए सुविधा बराबरको रकम रोजगारदाता स्वयंले दिनुपर्छ",
        ],
      },
    ],
    categorySlug: "claims-problems-solutions",
    userCategories: ["employee", "contributor"],
    popular: true,
    sourceKeys: ["act-2074"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "talab-ghatcha-ki",
    question: "३१% योगdान गर्दा श्रमिकको तलब घट्छ?",
    answerBlocks: [
      {
        type: "p",
        text: "श्रमिकको तर्फबाट कट्टा हुने ११% मध्ये १०% त पहिल्यैदेखि सञ्चय कोषमा जाने रकम हो — थप भार १% मात्र। रोजगारदाताको २०% तलबबाट होइन, माथि थपिन्छ। सबै रकम अन्ततः श्रमिककै सुविधा र बचतमा फर्किन्छ।",
      },
    ],
    categorySlug: "yogdan-ra-badfad",
    userCategories: ["employee"],
    popular: false,
    relatedArticleSlug: "yogdan-kasari-calculate-huncha",
    sourceKeys: ["procedure-2075-5th", "labour-act-2074"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "kati-dinbhitra-dakhila",
    question: "रोजगारदाताले योगदान कति दिनभित्र दाखिला गर्नुपर्छ?",
    answerBlocks: [
      {
        type: "p",
        text: "प्रत्येक नेपाली महिना समाप्त भएको २५ दिनभित्र (ऐन दफा ४, २०८२ संशोधन)। ढिलो भए १०% ब्याज लाग्छ र बैंक खाता/सम्पत्ति रोक्का, इजाजत निलम्बन, राहदानी रोक्कासम्मको कारबाही हुन सक्छ।",
      },
    ],
    categorySlug: "karmachari-ra-rojgardata",
    userCategories: ["employer"],
    popular: false,
    sourceKeys: ["act-2074"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "upachar-kaha-garne",
    question: "SSF बाट उपचार जहाँ गरे पनि पाइन्छ?",
    answerBlocks: [
      {
        type: "p",
        text: "कोषसँग सम्झौता भएका सूचीकृत अस्पतालमा सहज (क्यासलेस) हुन्छ। रोजगारीजन्य दुर्घटनामा सम्झौता नभएको अस्पतालमा उपचार गराउँदा ७ दिनभित्र कोषलाई जानकारी नगराए रु. ७ लाखभन्दा बढी कोषले व्यहोर्दैन। भुक्तानी दर स्वास्थ्य संस्था छनौट कार्यविधि, २०७६ अनुसार हुन्छ।",
      },
    ],
    categorySlug: "medical-maternity-accident-dependent",
    userCategories: ["contributor", "employee"],
    popular: false,
    videoIds: ["m2oKN85hFhU", "9LzsyY_4DsM"],
    sourceKeys: ["hospital-payment-2076", "procedure-2075-5th"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "upachar-sima-kati",
    question: "औषधि उपचारमा वार्षिक कति रकमसम्म पाइन्छ?",
    answerBlocks: [
      {
        type: "list",
        items: [
          "भर्ना भई उपचार: परिवारसमेत वार्षिक रु. १ लाखसम्म",
          "OPD/प्रेस्क्रिप्सन: वार्षिक रु. २० हजारसम्म (सीमाभित्रै)",
          "प्रत्येक दाबीको २०% आफैँले व्यहोर्नुपर्छ (सह-भुक्तानी)",
          "६० महिना योगदान गरेकालाई सूचीकृत अस्पतालमा रु. १–१० लाखको ५०% कोषले थप व्यहोर्छ",
          "घातक रोग: सेवा अवधिभर रु. १० लाखसम्म",
        ],
      },
    ],
    categorySlug: "medical-maternity-accident-dependent",
    userCategories: ["contributor", "employee", "family"],
    popular: false,
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "sutkeri-suvidha",
    question: "मातृत्व (सुत्केरी) सुविधा के-के पाइन्छ?",
    answerBlocks: [
      {
        type: "list",
        items: [
          "गर्भ परीक्षण, प्रसूति शल्यक्रिया/उपचार, सुत्केरीपछि ६ हप्तासम्मको उपचार र ३ महिनासम्मको शिशु उपचार (सीमाभित्र)",
          "प्रसूति स्याहार: प्रति शिशु एक महिनाको न्यूनतम पारिश्रमिक बराबर — २४ हप्तापछिको गर्भपतन/मृत शिशु जन्ममा पनि",
          "प्रसूति बिदा रकम: रोजगारदाताको ६० दिनबाहेकको अवधिमा आधारभूत पारिश्रमिकको ६०% (जम्मा ९८ दिनसम्म)",
          "पति-पत्नी दुवै योगदानकर्ता भए एकजनाले मात्र दाबी गर्न पाइन्छ",
        ],
      },
    ],
    categorySlug: "medical-maternity-accident-dependent",
    userCategories: ["employee", "family"],
    popular: false,
    videoIds: ["S_Ch2yO7G3A"],
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "mrityu-bhaema-pariwar",
    question: "योगदानकर्ताको मृत्यु भए परिवारले के पाउँछ?",
    answerBlocks: [
      {
        type: "list",
        items: [
          "पति/पत्नीलाई अन्तिम आधारभूत पारिश्रमिकको ६०% आजीवन मासिक (अर्को विवाह/वैकल्पिक रोजगारीमा रोकिन्छ)",
          "१८ वर्षमुनिका बढीमा २ सन्ततिलाई ४०% रकम दामासाहीले (अध्ययनरत भए २१ वर्षसम्म)",
          "पति/पत्नी र छोराछोरी नभए आश्रित बाबुआमालाई ६०% दामासाहीले",
          "अन्तिम संस्कार खर्च रु. २५,००० एकमुष्ट",
          "रोजगारीजन्य मृत्यु: पहिलो दिनदेखि; अन्य मृत्यु: कम्तीमा १२ महिना योगदान चाहिन्छ",
        ],
      },
    ],
    categorySlug: "medical-maternity-accident-dependent",
    userCategories: ["family", "contributor"],
    popular: false,
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "sapati-kasari-line",
    question: "SSF बाट सापटी (Loan) कसरी लिने?",
    answerBlocks: [
      {
        type: "p",
        text: "३६ महिना योगदान गरेकाले घर सापटी (रु. ७५ लाखसम्म, २० वर्ष) वा शैक्षिक सापटी (रु. ३५ लाखसम्म, १५ वर्ष) लिन सक्छन् — धितो चाहिन्छ। विशेष सापटी (अवकाश सुविधा रकमको ८०% सम्म) मा धितो चाहिँदैन र online/app बाटै आवेदन गर्न सकिन्छ।",
      },
    ],
    categorySlug: "pension-ra-retirement",
    userCategories: ["contributor"],
    popular: false,
    videoIds: ["KZ44YSrPkjY", "Ym8rVCfLfH0", "FTzJA0o_gnU"],
    sourceKeys: ["loan-directive-2079"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "sarkari-pension-ra-ssf",
    question: "सरकारी पेन्सन पाउनेले SSF निवृत्तभरण पनि पाउन सक्छ?",
    answerBlocks: [
      {
        type: "p",
        text: "सक्छ। कार्यविधिको दफा २४घ अनुसार नेपाल सरकार वा अन्यत्रबाट निवृत्तभरण पाइरहेको व्यक्तिले कोषमा योगदान गरी योग्य भएमा कोषबाट पनि निवृत्तभरण लिन बाधा पर्दैन।",
      },
    ],
    categorySlug: "pension-ra-retirement",
    userCategories: ["contributor"],
    popular: false,
    videoIds: ["8BLS0M5X6Os"],
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "dui-ssn-bhaema",
    question: "दुई वटा SSF नम्बर (SSN) भए के गर्ने?",
    answerBlocks: [
      {
        type: "p",
        text: "SSN जीवनभर एउटै हुनुपर्छ। गल्तीले दुई वटा बनेको भए तुरुन्तै कोषमा जानकारी दिई प्रमाण कागजातसहित एकीकरण (merge) गराउनुहोस् — नत्र योगदान विवरण बाँडिएर दाबीमा समस्या आउँछ।",
      },
    ],
    categorySlug: "kyc-profile-nominee",
    userCategories: ["contributor", "foreign"],
    popular: false,
    videoIds: ["nwdYoVHTEKA"],
    sourceKeys: ["listing-procedure-2075"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "sarkar-guarantee",
    question: "कोषको रकम सुरक्षित छ? सरकारले ग्यारेन्टी लिन्छ?",
    answerBlocks: [
      {
        type: "p",
        text: "ऐनको दफा ६२ अनुसार कोषको रकम अपर्याप्त भए योजनालाई निरन्तरता दिने दायित्व नेपाल सरकारको हुन्छ। कोषको रकम 'क' वर्गका बैंकमा राखिन्छ र लगानी कार्यविधि, २०७७ का सीमाभित्र रहेर लगानी हुन्छ।",
      },
    ],
    categorySlug: "ssf-parichaya",
    userCategories: ["employee", "contributor"],
    popular: false,
    sourceKeys: ["act-2074", "investment-procedure-2077"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "chhatrabritti",
    question: "योगदानकर्ताका छोराछोरीले छात्रवृत्ति पाउँछन्?",
    answerBlocks: [
      {
        type: "p",
        text: "पाउँछन्। कम्तीमा २४ महिना योगदान गरेका योगदानकर्ताका जेहेनदार सन्ततिले स्नातक तह अध्ययनका लागि वास्तविक शुल्क वा रु. ५ लाखमध्ये जुन कम हुन्छ, सो रकम छात्रवृत्ति पाउन सक्छन् (छात्रवृत्ति कार्यविधि, २०७९)। प्रत्येक वर्ष सूचना प्रकाशित हुन्छ।",
      },
    ],
    categorySlug: "medical-maternity-accident-dependent",
    userCategories: ["contributor", "family"],
    popular: false,
    sourceKeys: ["scholarship-2079"],
    lastVerified: LAST_VERIFIED,
  },
  {
    slug: "birami-bida-rakam",
    question: "लामो बिरामी हुँदा SSF बाट तलब पाइन्छ?",
    answerBlocks: [{ type: "p", text: "पाइन्छ। रोजगारदाताको वार्षिक १२ दिन बिरामी बिदाभन्दा लामो अवधि अस्पताल भर्ना वा चिकित्सकको सिफारिसमा घरमै उपचार गराउँदा आधारभूत पारिश्रमिकको ६०% रकम पाइन्छ — वार्षिक बढीमा १३ हप्तासम्म (कार्यविधि २०७५, दफा ७)।" }],
    categorySlug: "medical-maternity-accident-dependent",
    userCategories: ["employee"],
    popular: false,
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "ghatak-rog-suvidha",
    question: "घातक रोग (क्यान्सर, मृगौला) को उपचारमा कति पाइन्छ?",
    answerBlocks: [{ type: "list", items: [
      "सेवा अवधिभर जम्मा रु. १० लाखसम्म — क्यान्सर, मृगौला रोग, हृदय शल्यक्रिया, मस्तिष्कघात, पार्किन्सन्स, अल्जाइमर्स, spinal/head injury, थालासेमिया आदि",
      "योग्यता: पछिल्ला २८ महिनामा कम्तीमा २४ महिना नियमित योगदान",
      "रोग पहिचान खर्च रु. १ लाखसम्म; मेडिकल बोर्डको सिफारिसमा विदेशी अस्पताल रु. ७ लाखसम्म; डिस्चार्जपछिको पुनः परीक्षण रु. २ लाखसम्म",
    ]}],
    categorySlug: "medical-maternity-accident-dependent",
    userCategories: ["contributor", "family"],
    popular: false,
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "ashaktata-pratishat",
    question: "अशक्तता प्रतिशत कसले र कसरी तोक्छ?",
    answerBlocks: [{ type: "p", text: "स्वास्थ्य परीक्षण समितिले किटान गर्छ। निवृत्तभरण = आधारभूत पारिश्रमिकको ६०% × अशक्तता %, आजीवन र मुद्रास्फीति समायोजनसहित। २०% वा कम अशक्तता भए एकमुष्ट भुक्तानी हुनसक्छ। प्रत्येक ५ वर्षमा पुनरावलोकन हुन्छ — अन्तिम ५८ वर्षको उमेरमा।" }],
    categorySlug: "medical-maternity-accident-dependent",
    userCategories: ["contributor"],
    popular: false,
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "durghatana-7-din",
    question: "काममा दुर्घटना भयो — पहिलो काम के गर्ने?",
    answerBlocks: [{ type: "p", text: "७ दिनभित्र कोषलाई जानकारी गराउनुहोस् (रोजगारदाता, योगदानकर्ता वा परिवारले; message/email बाट पनि हुन्छ)। रोजगारीजन्य दुर्घटनाको पूरै उपचार खर्च कोषले व्यहोर्छ — तर जानकारी नगराई सम्झौता नभएको अस्पतालमा उपचार गराए रु. ७ लाखभन्दा बढी कोषले तिर्दैन।" }],
    categorySlug: "claims-problems-solutions",
    userCategories: ["employee", "employer"],
    popular: false,
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "employer-le-suchikaran-nagare",
    question: "रोजगारदाताले सूचीकरण गरिदिएन भने कर्मचारी आफैँले गर्न सक्छ?",
    answerBlocks: [{ type: "p", text: "सक्छ। रोजगारदाताले नगराए श्रमिक आफैँले कोषमा निवेदन दिन सक्छ — कोषले जाँचबुझ गरी १५ दिनभित्र सूचीकरण गराउन रोजगारदातालाई आदेश दिन्छ (सूचीकरण कार्यविधि २०७५, दफा ५)।" }],
    categorySlug: "karmachari-ra-rojgardata",
    userCategories: ["employee"],
    popular: false,
    sourceKeys: ["listing-procedure-2075"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "bidesh-bata-farkiepachhi",
    question: "विदेशबाट नेपाल फर्किएपछि SSF मा के गर्ने?",
    answerBlocks: [{ type: "p", text: "SSN उही रहन्छ। जागिरमा गए नयाँ रोजगारदाताले त्यही SSN मा योगदान गर्छ; व्यवसाय गरे स्वरोजगार योजनामा सर्नुहोस्; निवृत्तभरण योजनाको रकम एकमुष्ट लिने वा ÷१६० को आजीवन मासिक pension रोज्ने विकल्प पनि छ। KYC अद्यावधिक गर्न नबिर्सनुहोस्।" }],
    categorySlug: "baideshik-rojgari",
    userCategories: ["foreign"],
    popular: false,
    videoIds: ["DOaX_27N-ks"],
    sourceKeys: ["foreign-procedure-2079"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "60-pachhi-kaam",
    question: "६० वर्षपछि पनि काम गरिरहे योगदानको के हुन्छ?",
    answerBlocks: [{ type: "p", text: "श्रम सम्बन्ध कायम रहे योजना निरन्तर राख्न सकिन्छ — ६० वर्षपछिको नयाँ योगदान अवकाश सुविधा योजनामा जम्मा हुन्छ (दफा २४ङ)। निवृत्तभरण लिइरहेकाले मासिक pension को १% तिरेर आजीवन औषधि उपचार सुविधा पनि जारी राख्न सक्छन्।" }],
    categorySlug: "pension-ra-retirement",
    userCategories: ["contributor"],
    popular: false,
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "bideshi-nagarik",
    question: "विदेशी नागरिक कर्मचारीको SSF रकमको के हुन्छ?",
    answerBlocks: [{ type: "p", text: "रोजगार सम्बन्ध सकिएपछि वृद्ध अवस्था योजनाको सम्पूर्ण रकम एकमुष्ट फिर्ता लैजान पाउँछन् (दफा २४क)। नेपाली नागरिकता त्यागेकालाई पनि सोही व्यवस्था लागू हुन्छ।" }],
    categorySlug: "karmachari-ra-rojgardata",
    userCategories: ["employer", "employee"],
    popular: false,
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "dui-rojgardata",
    question: "एकैपटक दुई रोजगारदातामा काम गर्दा SSF कसरी मिलाउने?",
    answerBlocks: [{ type: "p", text: "एउटै SSN (PSSID) मा दुवै रोजगारदाता जोडिन सक्छन् — 'विभिन्न रोजगारदातामा PSSID थप गर्ने निवेदन' फारम भरेर। दुवैले आ-आफ्नो तलबको ३१% योगदान गर्छन्; रकम एउटै खातामा जम्मा हुन्छ। फारम हाम्रो Downloads page मा छ।" }],
    categorySlug: "kyc-profile-nominee",
    userCategories: ["employee"],
    popular: false,
    sourceKeys: ["listing-procedure-2075"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "talab-nabhaeko-mahina",
    question: "तलब नपाएको महिनाको योगदान कसले तिर्छ?",
    answerBlocks: [{ type: "p", text: "श्रमिकले पारिश्रमिक नपाउने अवस्था आए बढीमा ३ महिनासम्म निजको तर्फको योगदान रोजगारदाताले जम्मा गरिदिनुपर्छ — पछि श्रमिकको पारिश्रमिक/सुविधाबाट कट्टा गर्न सकिन्छ, तर मासिक ३३% भन्दा बढी होइन (ऐन दफा ८, नियमावली नियम ७)।" }],
    categorySlug: "yogdan-ra-badfad",
    userCategories: ["employee", "employer"],
    popular: false,
    sourceKeys: ["act-2074", "regulation-2075"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "swarojgar-adhar-parivartan",
    question: "स्वरोजगारले रोजेको आधार रकम पछि फेर्न मिल्छ?",
    answerBlocks: [{ type: "p", text: "मिल्छ — आधार न्यूनतम पारिश्रमिकदेखि ३ गुणासम्मको दायराभित्र रहनुपर्छ। आम्दानी बढ्दा आधार बढाए pension कोष पनि तीव्र बढ्छ; घटाउनु परे पनि योगदान नियमित राख्नुहोस्, नत्र उपचार सुविधा रोकिन्छ।" }],
    categorySlug: "karmachari-ra-rojgardata",
    userCategories: ["selfEmployed"],
    popular: false,
    relatedArticleSlug: "self-employed-guide",
    sourceKeys: ["informal-procedure-2079"],
    lastVerified: "2026-07-11",
  },
  {
    slug: "yogdan-badhaune-swechchhik",
    question: "तोकिएभन्दा बढी रकम स्वेच्छाले जम्मा गर्न मिल्छ?",
    answerBlocks: [{ type: "p", text: "मिल्छ — कोषलाई अग्रिम जानकारी दिई थप रकम स्वेच्छाले योगदान गर्न सकिन्छ; त्यो अवकाश सुविधा योजनामा जम्मा हुन्छ र चाहे pension योजनामा सारेर मासिक pension बढाउन पनि सकिन्छ (दफा २३, २३क)।" }],
    categorySlug: "pension-ra-retirement",
    userCategories: ["contributor"],
    popular: false,
    sourceKeys: ["procedure-2075-5th"],
    lastVerified: "2026-07-11",
  },
];

export function faqBySlug(slug: string): FaqItem | undefined {
  return faqs.find((f) => f.slug === slug);
}

export const popularFaqs = faqs.filter((f) => f.popular);
